version: 1
update_configs:
  # go modules
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - ":game_die: dependencies"
      - ":robot: bot"
